CREATE TABLE `students` (
	`id` text PRIMARY KEY NOT NULL,
	`candidate_number` text NOT NULL,
	`name` text NOT NULL,
	`identity_number` text NOT NULL,
	`student_number` text,
	`gender` text NOT NULL,
	`campus` text NOT NULL,
	`department_code` text NOT NULL,
	`department_name` text NOT NULL,
	`major_code` text NOT NULL,
	`major_name` text NOT NULL,
	`grade` integer NOT NULL,
	`class_name` text,
	`source_region` text,
	`program_duration` real NOT NULL,
	`study_status` text,
	`birth_date` text,
	`political_status` text,
	`ethnicity` text,
	`clothing_size` text,
	`shoe_size` text,
	`registration_status` text NOT NULL,
	`check_in_status` text NOT NULL,
	`checked_in_at` text,
	`subject_category` text NOT NULL,
	`subject_category_code` text,
	`subject_category_name` text,
	`graduation_school_code` text,
	`graduation_school_name` text,
	`landline_phone` text,
	`mobile_phone` text,
	`phone_contact` text,
	`postal_code` text,
	`mailing_recipient` text,
	`mailing_address` text,
	`candidate_category` text,
	`graduation_category` text,
	`admitted_major_name` text NOT NULL,
	`admission_province` text NOT NULL,
	`home_phone` text,
	`contact_phone` text,
	`pre_registration_status` text NOT NULL,
	`check_in_time_selection` text,
	`late_check_in_reason` text,
	`address_title` text,
	`address_longitude` real,
	`address_latitude` real,
	`administrative_division_code` text,
	`address_province` text,
	`address_city` text,
	`address_district` text,
	`address_street` text,
	`address_house_number` text,
	`address_confidence` integer,
	`address_precision` integer
);
